# Generated by Django 2.2 on 2020-01-01 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UsersApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question_profile',
            old_name='pro',
            new_name='profile',
        ),
        migrations.RenameField(
            model_name='question_profile',
            old_name='que',
            new_name='question',
        ),
        migrations.AddField(
            model_name='question_profile',
            name='ans',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='profile',
            name='phone',
            field=models.IntegerField(),
        ),
    ]
