# Generated by Django 2.2 on 2020-01-01 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UsersApp', '0002_auto_20200101_1105'),
    ]

    operations = [
        migrations.AddField(
            model_name='question_profile',
            name='is_correct',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
