# Generated by Django 2.2 on 2020-01-29 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RestUser', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile_second',
            name='tokenKey',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
